spec/dummy/config/application.rb, spec/dummy/config/environments/development.rb
When trying to set up development environment via `./bin/setup` using a new RVM gemset with Ruby 2.3.0 and Rails 5.0.0.1, the following error occures (caused by [these](https://github.com/palkan/logidze/blob/aaa44bae2c589917ae4455a7b053318f0e9465d9/spec/dummy/config/environments/development.rb#L28-L37) lines):
```
Resolving dependencies...
The Gemfile's dependencies are satisfied
Database 'dummy_development' already exists
Database 'logidze_test' already exists
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x00000001de17e0>
Did you mean?  asset_host
[ ... STACKTRACE ... ]
```
Steps to reproduce:
1. Create and enable a new RVM gemset:
````
$ rvm use 2.3.0  
$ rvm gemset create logidze-test
$ rvm gemset use logidze-test
````
2. Clone the …
=> Fix error when running ./bin/setup with Rails 5.0.0.1

lib/generators/logidze/install/templates/migration.rb.erb, lib/generators/logidze/model/model_generator.rb, lib/generators/logidze/model/templates/migration.rb.erb, spec/dummy/db/schema.rb, spec/generators/model_generator_spec.rb, spec/integrations/triggers_spec.rb, spec/support/acceptance_helpers.rb
Hello there,
It's my attempt to resolve #13 
I implemented two mutually exclusive options, `--whitelist` and `--blacklist`, both accepts arrays, like this: `--blacklist=title created_at` or `--whitelist active body`
I will be glad to fix any problems with this code and discuss any suggestions!
=> Columns filtering: blacklisting or whitelisting

lib/logidze/model.rb, spec/logidze/model_spec.rb
This fix will allow to use associations after `at` usage
=> Retain original object's id in `at` method

.rubocop.yml, CHANGELOG.md, README.md, lib/generators/logidze/install/templates/migration.rb.erb, lib/generators/logidze/model/model_generator.rb, lib/generators/logidze/model/templates/migration.rb.erb, logidze.gemspec, spec/dummy/db/migrate/20160415094739_create_users.rb, spec/dummy/db/schema.rb, spec/generators/model_generator_spec.rb, spec/integrations/timestamps_spec.rb, spec/integrations/triggers_spec.rb, spec/spec_helper.rb, spec/support/acceptance_helpers.rb, spec/support/matchers/use_timestamp.rb, spec/support/shared_contexts/setup_models_with_timestamps_column_context.rb
Hi! A lot of Rails models have an `updated_at` property which is used for many things. Wouldn't it be more logical and natural to take the value from the `updated_at` column and use it as version's timestamp? If the record's `updated_at` is `nil` or if the table doesn't have this column, version's timestamp will be set to `now()`.
```ruby
post = Post.create! # now()
post.update!        # updated_at
post = Post.create! # now()
post.update!        # now()
```
Also, it's a big benefit when testing. For example, I might want to use `Timecop.freeze` to freeze time and then update my record (e.x. testing my version decorator). However, `Timecop.freeze` will not affect SQL. If version's timestamp is the same as record's `updated_at`, freezing time becomes trivial.
Let me know what you think …
=> Default version timestamp to "updated_at"

CHANGELOG.md, README.md, lib/logidze.rb, lib/logidze/model.rb, spec/integrations/triggers_spec.rb
Our team has encountered a situation where we want Logidze to preserve "future" versions of the record when an older (restored) version is updated. I imagine that this would be a fairly common case, so I propose we add a generator option for that. Example: 
```ruby
rails generate logidze:model Post
post = Post.create!(title: 'first post') # v1
post.update!(title: 'some post')         # v2
post.undo!                               # v1
post.update!(title: 'my post')           # v2
rails generate logidze:model Post --no-overwrite
post = Post.create!(title: 'first post') # v1
post.update!(title: 'some post')         # v2
post.undo!                               # v1
post.update!(title: 'my post')           # v3
```
@palkan, what do you think? Should we add some kind of a `delete_version` …
=> Add an option to append versions to the log upon undo

.rubocop.yml, CHANGELOG.md, Gemfile, README.md, Rakefile, lib/generators/logidze/model/model_generator.rb, lib/logidze/has_logidze.rb, lib/logidze/history.rb, lib/logidze/model.rb, lib/logidze/versioned_association.rb, logidze.gemspec, spec/acceptance_helper.rb, spec/dummy/db/migrate/20160415094739_create_users.rb, spec/dummy/db/migrate/20160415194001_create_posts.rb, spec/dummy/db/schema.rb, spec/integrations/triggers_spec.rb, spec/logidze/model_spec.rb, spec/support/acceptance_helpers.rb, spec/support/shared_contexts/cleanup_files_contexts.rb, spec/support/test_helpers.rb
=> Handle serialized types

lib/generators/logidze/install/templates/migration.rb.erb, spec/integrations/triggers_spec.rb
Addressing #53 
Not really sure about necessity of checking snapshot on `INSERT` though :) On the one hand it‘s hard to imagine one‘s blacklisting _all_ columns of the model. On the other — everything is possible. Testing it also will require some rearrangement in spec.
=> Fix creating empty versions, when only blacklisted columns are updated

spec/support/shared_contexts/cleanup_files_contexts.rb
Since Rails 5.2.0 all class methods from `ActiveRecord::Migrator` reside in `ActiveRecord::MigrationContext`, so we should use it to obtain all migration versions
=> Use migration_context, if available (Rails 5.2.0)

CHANGELOG.md, lib/generators/logidze/install/templates/migration.rb.erb, lib/generators/logidze/model/model_generator.rb, lib/logidze/version.rb, spec/generators/model_generator_spec.rb, spec/integrations/triggers_spec.rb
Usecase: We have a `Blog` model which get frequent minor updates for the `content` column as the editor keeps typing with the CMS autosave feature (every 5s) and we don't want to create log to capture tiny changes. The content text could be big so we need to save space. I came up with a concept similar to https://underscorejs.org/#debounce. The idea is that if the several logs came in within a time period, we only keep the latest one and discard the rest. 
```
{
"h": [
{
"c": {
"content": "Content 1"
},
"v": 1,
"ts": 0
},
{
"c": {
"content": "content 2"
},
"v": 2,
"ts": 100
},
{
"c": {
"content": "content 3"
},
"v": 3,
"ts": 101
}
],
"v": 3
}
```
becomes
```
{
"h": [
{
"c": {
"content": "Content 1"
},
"v": 1,
"ts": 0
},
{
"c": {
"content": "content 3"
},
"v": 3,
"ts": 101
}
],
"v": 3
} …
```
=> Adding debounce time to avoid spamming changelog creation

lib/logidze/model.rb, spec/logidze/model_spec.rb
Resolves https://github.com/palkan/logidze/issues/92
log_size method returns 0 when log_data is nil
=> Return 0 for log size when log_data is nil

CHANGELOG.md, README.md, lib/logidze.rb, lib/logidze/has_logidze.rb, lib/logidze/ignore_log_data.rb, lib/logidze/ignore_log_data/cast_attribute_patch.rb, lib/logidze/ignore_log_data/ignored_columns.rb, lib/logidze/ignore_log_data/missing_attribute_patch.rb, lib/logidze/model.rb, spec/dummy/app/models/not_logged_post.rb, spec/dummy/app/models/post.rb, spec/dummy/app/models/user.rb, spec/dummy/db/migrate/20160415194001_create_posts.rb, spec/dummy/db/schema.rb, spec/integrations/ignore_log_data_spec.rb, spec/logidze/model_spec.rb
=> Add :ignore_log_data option to #has_logidze

CHANGELOG.md, README.md, lib/logidze/model.rb, spec/logidze/model_spec.rb
#108 This commit add class method .reset_log_data for nullify
association and instance method #reset_log_data for nullify
single record.
=> Add API to nullify log_data column

CHANGELOG.md, README.md, lib/logidze.rb, lib/logidze/has_logidze.rb, lib/logidze/ignore_log_data.rb, lib/logidze/ignore_log_data/association.rb, lib/logidze/ignore_log_data/default_scope_patch.rb, lib/logidze/ignore_log_data/ignored_columns.rb, lib/logidze/ignore_log_data/missing_attribute_patch.rb, spec/dummy/app/models/always_logged_post.rb, spec/dummy/app/models/comment.rb, spec/dummy/app/models/not_logged_post.rb, spec/dummy/app/models/not_logged_post_comment.rb, spec/dummy/db/migrate/20180315522153_create_post_comments.rb, spec/dummy/db/schema.rb, spec/integrations/ignore_log_data_spec.rb
This is the implementation of #109. The idea is that we store a list of models that allow overriding the global setting (i.e. where `:ignore_log_data` is not specified) and when global setting is changed - we start or stop ignoring the `log_data` column.
=> Global configuration for :ignore_log_data option

README.md
This is a small change in the README, as the items suppose to be separated by comma when using `[black|white]list`.
=> [@cristofer] Fixing small mistake in README (comma for items in black/white lists)

CHANGELOG.md, README.md, lib/logidze/meta.rb, spec/integrations/meta_spec.rb
Adds support for setting meta without the database transaction block.
I've added the possibility to specify if meta information should be set within the transaction block or not. For this I have added the optional argument to the .with_meta method and split the MetaTransaction class into 3 separate classes, MetaWrapper, MetaWithTransaction and MetaWithoutTransaction. 
...
=> Add support for setting meta without transaction block

README.md
It was non-obvious to me that the `--update` option for the `logidze:model` migration didn't carry over the existing whitelist/blacklist, and that this needed to be explicitly specified again. I wanted to make sure to note that for others. Thanks for the amazing gem!
=> Clarify 1.0 upgrade instructions for models

CHANGELOG.md, lib/generators/logidze/install/functions/logidze_snapshot.sql, spec/logidze/create_snapshot_spec.rb, spec/sql/snapshot_spec.rb
=> Stringify snapshot jsonb values

CHANGELOG.md, README.md, lib/generators/logidze/model/model_generator.rb, spec/generators/model_generator_spec.rb
Fixes #205
As described in #205, currently when someone does `rails generate logidze:model MyModel` and then wants to revoke that generation with `rails destroy logidze:model MyModel`, the injected `has_logidze` is removed from the model file, but the created migration file is not deleted. This PR fixes that.
Remove the `migration_file_name` method from `ModelGenerator` entirely.
After digging, I discovered that this method was clobbering an `attr_accessor` of the same name in the underlying generator plumbing in `Rails::Generators::Migration` (`lib/rails/generators/migration.rb` in `railties`), which was causing the `migration_exists?` in that same file not to work as expected. This was, in turn, causing code in `Rails::Generators::Actions::CreateMigration` …
=> fixing issue where destroy fails to delete file

.github/workflows/docs-lint.yml, .github/workflows/rspec.yml
Adds Ruby 3.2 to the CI matrix.
Also updates the checkout and cache action versions.
To ensure the gem is tested against Ruby 3.2
Updated CI
Nope
=> Adds Ruby 3.2 to the CI matrix

CHANGELOG.md, lib/logidze/model.rb, spec/integration/triggers_spec.rb, spec/logidze/model_spec.rb
Fixes #217
Additionally, I've added a log_data check in `switch_to!`. When `append` is false the check would happen in `at_version!`, but when it's true the method would fail.
Now we always check and raise on nil.
=> Switch to fix

lib/logidze/model.rb, spec/logidze/model_spec.rb
Suggest a behavior change to the model's `#at` and `#at_version` methods (non-exclamation-mark versions).
When using `#at(version: v)` or `#at_version(v)` to attempt to get a specific version of a model instance, but `log_data` hasn't been set yet, return `nil` instead of the current behavior.
The current behavior is to raise `NoMethodError` ("undefined method 'version' for nil:NilClass"). For the non-exclamation-point versions of these methods, I believe it is less surprising to instead get `nil`.
Please let me know if you like this idea, but would like some changes to this PR (such as actually mentioning this edge-case in the README.md).
=> Return nil when getting a version and there's no log_data

CHANGELOG.md, README.md, lib/logidze/model.rb, spec/logidze/model_spec.rb
Add retrieving [list of versions support](https://github.com/palkan/logidze/issues/212)
Added `#logidze_versions` method which retrieves list of versions of model depending on options provided (`reverse` and `include_self`
If `reverse` is provided, reversed Enumerator will be returned.
If `include_self` is provided, the list will contain also current version of the model.
=> Add retrieving list of versions support

CHANGELOG.md, README.md
Saw this today, and wanted to use it, and learned that README is all wrong 😅
It was implemented as `#logidze_versions` in #238.
And here are the results:
```
irb(main):043> cafe.logidze_versions.map{|v| v.log_version}
=> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
irb(main):044> cafe.logidze_versions(reverse: true).map{|v| v.log_version}
=> [12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
irb(main):045> cafe.logidze_versions(include_self: true).map{|v| v.log_version}
=> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
irb(main):046> cafe.logidze_versions(reverse: true, include_self: true).map{|v| v.log_version}
=> [13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
```
So most of the readme of this method is currently wrong 🙈
Fix README and CHANGELOG to be correct.
=> Replace #versions with #logidze_versions in README

CHANGELOG.md, README.md, lib/logidze.rb, lib/logidze/engine.rb
Fixes #250 
This PR allows for a configurable option to declare how the ordering of the triggers are generated as part of the schema dump.
* added a configurable option for `Logdize.order_by_trigger_name` that defaults to `false`
* when set to true, a module is prepended `Fx::Adapters::Postgres::Triggers` to ensure the returned value is sorted by `name`
I'm not sure the best way to test this. I've tested my branch locally against an active project and this is resolving the issue I described.
=> support ordering of triggers by name

CHANGELOG.md, lib/generators/logidze/model/model_generator.rb, spec/generators/model_generator_spec.rb
Fix an issue where running `rails d logidze:model` doesn’t remove the `fx` trigger file since it was incrementing the trigger version and attempting the next version instead of the current version.
Updated the `#next_version` method to return the current version when the task behavior is `:revoke`.
=> Fix destroy not deleting `fx` trigger file

.github/workflows/rspec.yml, gemfiles/rails8.gemfile, logidze.gemspec
fd67403e265d3735d4dbe75bca4f06c2e886c7b1 fixes the Rspec matrix in CI - this [was broken in 2023](https://github.com/palkan/logidze/commit/d2f77afd3ca05d15b09738273bb3961d7d2bbc70#diff-1fadaba7942eb03a370984f465dc59789417e580083e4bcaa2d073959b1815beL100-L105), as the env variable to set the gemfile was added to other workflow files, but not the rsped one.
dfd2b2736cb827f096f695ff57e9c8c5c113e717 modernizes the workflow (no need to manually install libpq anymore)
83480a82ba86940d5674496b1e8855774b5f8aaa adds Rails 8 to the matrix and modernizes the ruby/postgres versions the gem is tested with.
77d350f11230f9c2673c6d940fdfee36fd62a385 is needed due to https://github.com/rails/rails/issues/54263, don't think it is desirable to merge.
The specs fail against Rails master, unsure how to fix …
=> Fix Rspec workflow in CI, add Rails 8 to matrix

README.md
This PR improves the documentation around the detached mode:
- **Fixes incorrect command**
The example now correctly uses `rails generate logidze:model` instead of the invalid `rails logidze:model`.
- **Adds missing note on logidze_data table**
Documents the migration step for creating the shared `logidze_data` table, which is required when using detached mode.
- **Adds note on upgrading logidze_logger**
Older versions of `logidze_logger` (e.g. `logidze_logger_v02`) do not support detached mode and raise errors like:
```
ERROR:  record "old" has no field "log_data" (PG::UndefinedColumn)  
CONTEXT: SQL expression "OLD.log_data is NULL OR OLD.log_data = '{}'::jsonb"  
PL/pgSQL function logidze_logger() line 46 at IF  
```
=> docs: fix detached mode example and add key missing notes

CHANGELOG.md, README.md, lib/logidze/meta.rb, spec/integration/meta_spec.rb
Fixes #202
Provide `Logidze.with_meta!` and `Logidize.with_responsible!` to attach these details permanently instead of for the duration of a block.  This resolves #202 and allows the behavior outlined in #200:
```
console do
Logidze.with_responsible(current_user.id)
end
```
It also considers feedback in the attempt from #203.
Finally, this resolves #221, although using this in web requests comes with its own risks.
In `Logidze::Meta`
* New class `MetaBase` pulling meta stack management from `MetaWrapper`
* New class `MetaForConnection` to manage metadata for bang methods
* New method `.with_meta!` to set metadata with no implicit end
* New method `.with_responsible!` to set actor id with no implicit end
* New method `.clear_meta!` to explicitly clear metadata
I'm not sure how I feel …
=> Provide bang versions of meta methods
