- CHANGELOG.md
- README.md
- lib/generators/logidze/install/install_generator.rb
- lib/generators/logidze/install/templates/migration.rb.erb
- lib/generators/logidze/model/model_generator.rb
- lib/generators/logidze/model/templates/migration.rb.erb
- lib/logidze.rb
- lib/logidze/has_logidze.rb
- lib/logidze/history.rb
- lib/logidze/history/version.rb
- lib/logidze/model.rb
- lib/logidze/responsible.rb
- lib/logidze/version.rb
- spec/acceptance/migrations_spec.rb
- spec/dummy/app/models/custom_user.rb
- spec/dummy/app/models/post.rb
- spec/dummy/app/models/user.rb
- spec/dummy/db/migrate/20160415094739_create_users.rb
- spec/dummy/db/schema.rb
- spec/generators/install_generator_spec.rb
- spec/generators/model_generator_spec.rb
- spec/integrations/responsible_spec.rb
- spec/integrations/triggers_spec.rb
- spec/logidze/model_spec.rb
- spec/support/acceptance_helpers.rb
- spec/support/shared_contexts/cleanup_files_contexts.rb
- spec/support/test_helpers.rb
> Add ability to track responsibility

- README.md
> Fix JSON structure in README

- CHANGELOG.md
- README.md
- lib/generators/logidze/model/model_generator.rb
- lib/logidze/version.rb
- spec/generators/model_generator_spec.rb
> Add path option to model generator

- lib/generators/logidze/install/templates/migration.rb.erb
> Drop *all* created functions upon rolling back

- lib/generators/logidze/install/templates/hstore.rb.erb
> Converting tabs to spaces in hstore migration

- CHANGELOG.md
- lib/logidze/model.rb
- spec/logidze/model_spec.rb
> Ignore missing columns in diff and past versions

- CHANGELOG.md
- lib/logidze/versioned_association.rb
- spec/dummy/app/models/article.rb
- spec/logidze/model_spec.rb
> Fix for association versioning with an optional belongs to

- README.md
A small addition to the Log format readme section related to the meta functionality
> Update Log format section in README with details about meta

- CHANGELOG.md
- README.md
- lib/logidze/model.rb
- spec/integrations/create_snapshot_spec.rb
- spec/sql/snapshot_spec.rb
Add API to populate initial `log_data`.
> Add #create_logidze_snapshot! method

- lib/logidze/model.rb
- spec/integration/ignore_log_data_spec.rb
Fixes #163
Explicitly set table name in reload_log_data + provided test to reproduce it
> Explicitly set table_name in pluck in reload_log_data

- spec/integration/ignore_log_data_spec.rb
Sorry for broken tests, this fixes expectation of that test
> Fixes expectation in default scope test

- CHANGELOG.md
- README.md
- lefthook.yml
- lib/generators/logidze/model/model_generator.rb
- spec/generators/model_generator_spec.rb
> Add --name option to model generator

- spec/logidze/associations_spec.rb
I found typo in spec file and fixed it.
> Fixed typo

- CHANGELOG.md
- lib/generators/logidze/install/templates/hstore.rb.erb
- lib/generators/logidze/install/templates/migration.rb.erb
- lib/generators/logidze/install/templates/migration_fx.rb.erb
- lib/generators/logidze/model/templates/migration.rb.erb
- spec/generators/install_generator_spec.rb
- spec/generators/model_generator_spec.rb
> Set dynamic ActiveRecord version for migrations

- README.md
> Add article and update table of contents

- CHANGELOG.md
- gemfiles/rails52.gemfile
- gemfiles/rails6.gemfile
- gemfiles/railsmaster.gemfile
- logidze.gemspec
Remove Rails meta-gem dependency
Remove Rails meta-gem dependency
Closes https://github.com/palkan/logidze/issues/184
Nope
> Remove Rails meta-gem dependency

- CHANGELOG.md
- README.md
- bench/triggers/Makefile
- bench/triggers/Readme.md
- bench/triggers/hstore_with_fallback_setup.sql
- lib/generators/logidze/install/functions/logidze_capture_exception.sql
- lib/generators/logidze/install/functions/logidze_logger.sql
- spec/generators/install_generator_spec.rb
- spec/integration/triggers_spec.rb
- spec/logidze/utils/function_definitions_spec.rb
This adds:
- handler for the `NUMERIC_VALUE_OUT_OF_RANGE` exception
- `logidze_capture_exception(error_data jsonb)` function which allows to add custom behavior on exception
Closes #193
> Handling PG exceptions

- CHANGELOG.md
- lib/generators/logidze/install/functions/logidze_logger.sql
- lib/generators/logidze/install/functions/logidze_snapshot.sql
- lib/generators/logidze/install/functions/logidze_version.sql
- lib/logidze/model.rb
- spec/generators/install_generator_spec.rb
- spec/integration/triggers_spec.rb
- spec/logidze/model_spec.rb
- spec/logidze/utils/function_definitions_spec.rb
> Skip log_data column during apply_column_diff

- README.md
- [] I've updated a documentation (Readme)
> Fixes pending_upgrade mistype in README

- bench/performance/app/lib/benchmarker.rb
- bench/performance/benchmarks/update_bench.rb
- bench/performance/db/functions/logidze_logger_v01.sql
- bench/performance/db/migrate/20200720094739_create_users.rb
- lib/generators/logidze/install/functions/logidze_logger.sql
- spec/dummy/db/migrate/20160415194001_create_posts.rb
- spec/generators/install_generator_spec.rb
- spec/integration/triggers_spec.rb
- spec/logidze/utils/function_definitions_spec.rb
Fixes #209.
I don't think it's a good idea to create a custom comparison operator for a built-in type (also it wouldn't work in this case anyway), so I think casting pseudorecords to JSONB before comparing them is a better workaround.
Honestly, a better solution would be to use JSONB over JSON in most cases. So chances of running into this issue are pretty low, but a bug is a bug.
> fix: support JSON columns

- CHANGELOG.md
The tiniest of tiniest changes. I forgot to include myself in #218 🤦‍♂️
> Add miharekar link
